"""Shared geometry values for the OpenPulsar interface.

Keeping these values in one place prevents visually identical panels from
slowly drifting apart as the UI evolves.
"""

PANEL_RADIUS = 12
PANEL_BORDER_WIDTH = 1

HEADER_HEIGHT = 28
PANEL_BODY_HEIGHT = 360
PANEL_HEIGHT = HEADER_HEIGHT + PANEL_BODY_HEIGHT

LEFT_PANEL_WIDTH = 340
DPI_PANEL_WIDTH = 180
PANEL_GAP = 8
PROFILE_TO_MAIN_GAP = 12
MAIN_TO_SENSOR_GAP = 4
PROFILE_RIBBON_WIDTH = LEFT_PANEL_WIDTH + PANEL_GAP + DPI_PANEL_WIDTH

CONTENT_MARGIN_X = 8
CONTENT_MARGIN_TOP = 12
CONTENT_MARGIN_BOTTOM = 10
ROW_HEIGHT = 38
ROW_SPACING = 10
FOOTER_HEIGHT = 38
